# Generated by Django 5.1.7 on 2025-03-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchasedetail',
            options={'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalles de Compra'},
        ),
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'verbose_name': 'Venta de Producto', 'verbose_name_plural': 'Ventas de Producto'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='toolmaintenance',
            options={'verbose_name': 'Mantenimiento de Herramienta', 'verbose_name_plural': 'Mantenimientos de Herramientas'},
        ),
        migrations.AlterModelOptions(
            name='workingday',
            options={'verbose_name': 'Jornada de Trabajo', 'verbose_name_plural': 'Jornadas de Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='workingdayresource',
            options={'verbose_name': 'Recurso de Jornada de Trabajo', 'verbose_name_plural': 'Recursos de Jornadas de Trabajo'},
        ),
        migrations.AddField(
            model_name='workingday',
            name='tool_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
