# Generated by Django 5.1.7 on 2025-03-29 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workingdays', to='apis_.collaborator', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workings', to='apis_.task', verbose_name='Tarea'),
        ),
    ]
