# Generated by Django 5.1.7 on 2025-03-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdayresource',
            name='working_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='apis_.workingday', verbose_name='Jornada laboral'),
        ),
    ]
