# Generated by Django 5.1.7 on 2025-03-26 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='charged',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='discount_reazon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Descuento'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='kilos',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=18, verbose_name='kilos'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='price_kilo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Precio de Kilo'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Otro descuento'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarifa'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='tool_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Uso de herramienta'),
        ),
    ]
