# Generated by Django 5.1.7 on 2025-03-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0002_alter_workingdayresource_working_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolmaintenance',
            options={'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Existencias'),
        ),
    ]
