# Generated by Django 5.1.7 on 2025-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0002_alter_saleproduct_options_saleproduct_charged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='charged',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Cobrado S/'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='discount_reazon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo(s) de Descuento'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Total S/'),
        ),
    ]
