# Generated by Django 5.1.7 on 2025-03-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0002_alter_article_options_alter_collaborator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tool_discount',
        ),
    ]
