# Generated by Django 5.1.7 on 2025-03-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0003_alter_toolmaintenance_options_alter_article_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdayresource',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cantidad'),
        ),
    ]
