# Generated by Django 5.1.7 on 2025-03-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0003_saleproduct_is_paid_alter_saleproduct_charged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=15, verbose_name='Celular')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=15, verbose_name='Celular')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=15, verbose_name='Celular')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
    ]
