# Generated by Django 5.1.7 on 2025-03-25 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0003_remove_task_tool_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedetail',
            options={'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalles de Compras'},
        ),
        migrations.RemoveField(
            model_name='workingday',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='workingday',
            name='is_done',
            field=models.BooleanField(default=True, verbose_name='Concluida'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Existencias'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('product', 'Producto'), ('tool', 'Herramienta')], default='product', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='um',
            field=models.CharField(max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='provider',
            field=models.TextField(verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='apis_.article', verbose_name='Articulo'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='apis_.purchase', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='units',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='client',
            field=models.TextField(blank=True, null=True, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='kilos',
            field=models.IntegerField(default=1, verbose_name='kilos'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='price_kilo',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=18, verbose_name='Precio de Kilo'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=18, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pay_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago por día'),
        ),
        migrations.AlterField(
            model_name='toolmaintenance',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='apis_.article', verbose_name='Herramienta'),
        ),
        migrations.AlterField(
            model_name='toolmaintenance',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='toolmaintenance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Reparación'),
        ),
        migrations.AlterField(
            model_name='toolmaintenance',
            name='provider',
            field=models.TextField(blank=True, null=True, verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Pendiente'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_.collaborator', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Jornada'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_.task', verbose_name='Tarea'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='tool_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento por herramienta'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='use_own_tool',
            field=models.BooleanField(default=True, verbose_name='Usa Herramienta Propia'),
        ),
        migrations.AlterField(
            model_name='workingdayresource',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_.article', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='workingdayresource',
            name='units',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='workingdayresource',
            name='working_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_.workingday', verbose_name='Jornada laboral'),
        ),
    ]
