# Generated by Django 5.1.7 on 2025-03-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0004_customer_provider_technical_collaborator_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolmaintenance',
            name='provider',
        ),
    ]
