# Generated by Django 5.1.7 on 2025-03-29 08:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0004_alter_purchase_is_paid_alter_saleproduct_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Ingresado S/'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Generado S/'),
        ),
    ]
