# Generated by Django 5.1.7 on 2025-03-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0005_alter_workingday_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='provider',
            field=models.CharField(max_length=100, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='client',
            field=models.CharField(default='Ninguno', max_length=100, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='toolmaintenance',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnico'),
        ),
    ]
