# Generated by Django 5.1.7 on 2025-03-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0005_remove_toolmaintenance_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sales', to='apis_.provider', verbose_name='Proveedor'),
        ),
    ]
