# Generated by Django 5.1.7 on 2025-03-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0006_alter_purchase_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='client',
        ),
    ]
