# Generated by Django 5.1.7 on 2025-03-26 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0007_remove_saleproduct_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoppings', to='apis_.purchase', verbose_name='Cliente'),
        ),
    ]
