# Generated by Django 5.1.7 on 2025-03-26 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0008_saleproduct_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolmaintenance',
            name='technical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='apis_.provider', verbose_name='Técnico'),
        ),
    ]
