# Generated by Django 5.1.7 on 2025-03-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0009_toolmaintenance_technical'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolmaintenance',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='toolmaintenance',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='toolmaintenance',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pagado'),
        ),
    ]
