# Generated by Django 5.1.7 on 2025-03-26 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0011_alter_saleproduct_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technical',
            options={'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='lastname',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Cliente desconocido', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(default='Proveedor desconocido', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technical',
            name='name',
            field=models.CharField(default='Taller desconocido', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toolmaintenance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
