# Generated by Django 5.1.7 on 2025-03-26 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0012_alter_technical_options_remove_customer_firstname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technical',
            new_name='Workshop',
        ),
        migrations.RemoveField(
            model_name='toolmaintenance',
            name='technical',
        ),
        migrations.AddField(
            model_name='toolmaintenance',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='apis_.workshop', verbose_name='Taller'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
    ]
