# Generated by Django 5.1.7 on 2025-03-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0013_rename_technical_workshop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingday',
            old_name='pay',
            new_name='tariff',
        ),
        migrations.RemoveField(
            model_name='workingday',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='workingday',
            name='tool_discount',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento'),
        ),
    ]
