# Generated by Django 5.1.7 on 2025-03-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0014_rename_pay_workingday_tariff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='city',
            new_name='address',
        ),
    ]
