# Generated by Django 5.1.7 on 2025-03-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0015_rename_city_collaborator_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
    ]
