# Generated by Django 5.1.7 on 2025-03-27 15:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_', '0016_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Descuento'),
        ),
    ]
